//to use in PriceTicker.tsx
  export const symbols = [
    "BTC/USD",
    "ETH/USD",
    "SOL/USD",
    "XRP/USD",
    "ADA/USD",
    "DOGE/USD",
    "AVAX/USD",
    "DOT/USD",
    "LINK/USD",
    "LTC/USD",
  
    "BCH/USD",
    "XLM/USD",
    "ATOM/USD",
    "UNI/USD",
    "AAVE/USD",
    "FIL/USD",
    "ETC/USD",
    "NEAR/USD",
    "ALGO/USD",
    "ICP/USD",
  
    "SUI/USD",
    "APT/USD",
    "ARB/USD",
    "OP/USD",
    "INJ/USD",
    "SEI/USD",
    "RENDER/USD",
    "GRT/USD",
    "LDO/USD",
  
    "COMP/USD",
    "SNX/USD",
    "CRV/USD",
    "SAND/USD",
    "MANA/USD",
    "AXS/USD",
    "CHZ/USD",
    "GALA/USD",
  
    "PEPE/USD",
    "SHIB/USD",
    "BONK/USD",
    "FLOKI/USD",
    "WIF/USD",
    "TRX/USD",
    "HBAR/USD",
    "VET/USD",
  
    "KAVA/USD",
    "RUNE/USD",
    "IMX/USD",
    "STX/USD",
    "QNT/USD",
    "ZEC/USD",
    "DASH/USD",
    "XTZ/USD",
    "EGLD/USD",
    "THETA/USD",

  ];