export const COINBASE_SYMBOLS = [
    "BTC/USD",
    "ETH/USD",
    "SOL/USD",
    "XRP/USD",
    "ADA/USD",
    "DOGE/USD",
    "AVAX/USD",
    "DOT/USD",
    "LINK/USD",
    "LTC/USD",
  
    "BCH/USD",
    "XLM/USD",
    "ATOM/USD",
    "UNI/USD",
    "AAVE/USD",
    "FIL/USD",
    "ETC/USD",
    "NEAR/USD",
    "ALGO/USD",
    "ICP/USD",
  
    "SUI/USD",
    "APT/USD",
    "ARB/USD",
    "OP/USD",
    "INJ/USD",
    "SEI/USD",
    "RENDER/USD",
    "GRT/USD",
    "LDO/USD",
    "MKR/USD",
  
    "COMP/USD",
    "SNX/USD",
    "CRV/USD",
    "SAND/USD",
    "MANA/USD",
    "AXS/USD",
    "CHZ/USD",
    "SHIB/USD",
    "BONK/USD",
    "WIF/USD",
  
    "HBAR/USD",
    "KAVA/USD",
    "RUNE/USD",
    "IMX/USD",
    "STX/USD",
    "QNT/USD",
    "ZEC/USD",
    "XTZ/USD",
    "JASMY/USD",
    "LPT/USD",
    "ENS/USD",
    "MASK/USD",
  ] as const;